### ISSUE TITLE
First card won't load

### ISSUE THREAD

**Issue by Ratonu13** [zjosua/anki-mc#45] opened 2021-03-18 15:53 UTC
updated to v2.4.0, I have the same issue, but pressing edit still doesn't load the card. I can load the other cards after that if I click show answer for the first (it shows a blank card), then it works smoothly. It ruins the scheduling for that first card, unfortunately.

Edit: also getting the missing packaging error

_Originally posted by @Ratonu13 in https://github.com/zjosua/anki-mc/issues/32#issuecomment-801698888_

**Comment by 3ter** [comment] 2021-03-18 16:06
Thank you for your observation. Please don't open another issue for something that has (hopefully) been fixed :slightly_smiling_face: .

See my https://github.com/zjosua/anki-mc/issues/44#issuecomment-801827123 for an explanation. If you want to try and repair it manually until the dependencies are added to the distributable you can either
* copy the contents of [those three files](https://github.com/zjosua/anki-mc/tree/master/card) into your respective cards in the Multiple Choice note type
* clone the git repository to your system with `git clone --recursive git@github.com:zjosua/anki-mc.git` and copy the `packaging` folder into the addon folder

**Comment by 3ter** [comment] 2021-03-18 18:07
Thanks to @zjosua all dependencies are now included in the release and the update worked fine for me.

@Ratonu13 Please have a look running anki 2.1.42 / addon 2.4.1.

**Comment by Ratonu13** [comment] 2021-03-19 08:49
> 
> 
> Thanks to @zjosua all dependencies are now included in the release and the update worked fine for me.
> 
> @Ratonu13 Please have a look running anki 2.1.42 / addon 2.4.1.

Updated and still the same. The start error went away so nothing to do with that. I mainly use anki on my phone which works so if I'm the only one with this bug I don't really mind it

**Comment by 3ter** [comment] 2021-03-19 14:02
Actually I couldn't reproduce it on Linux or Windows. Only weird thing that happened is when first updating the addon with the new `packaging` folder `anki` hangs for me in the sync process. This can be something related to my collection though. It happened on both OS as well.

**Comment by 3ter** [comment] 2022-10-30 14:31
Resolved by latest updates

**Closed by 3ter** 2022-10-30 14:31 UTC
