### ISSUE TITLE
Enable/Disable shuffling?

### ISSUE THREAD

**Issue by K1NGM4RV** [zjosua/anki-mc#57] opened 2021-08-05 20:40 UTC
Hello everyone! Is is possible to **turn off the shuffling** somehow? 
Also: is it possible to make the squares in front of the question bigger?

Thank you very much and best regards!
Marvin

**Comment by K1NGM4RV** [comment] 2021-08-06 11:38
Just deleting the "onShuffle();" function from the front card will disable the shuffling!

**Comment by 3ter** [comment] 2022-10-30 10:14
Closing as duplicate of #87 (which has more current information)

**Closed by 3ter** 2022-10-30 10:14 UTC
