### ISSUE TITLE
Does it work on iOS?

### ISSUE THREAD

**Issue by aminix** [zjosua/anki-mc#14] opened 2020-08-13 23:16 UTC
Hi,

I have downloaded the latest Anki for desktop macOS and the latest app for iOS.

This plugin works fine in desktop but in mobile the behaviour for the multiple choice type (checkbox) is that it shows the answer immediately without checking the checkbox. 

Expected behaviour: when is a multiple choice type, a tap should select an option and the user should be able to keep selecting options.

Is this known? Is there a special config I need to set?

Thanks!

**Comment by zjosua** [comment] 2020-09-15 12:30
Anki Mobile (the iOS app) interprets a tap on the question area as the "Show Answer" command.
I am not sure if the app settings allow to change this (I don't own the iOS app).

Maybe a "long tap" works to check the boxes, while avoiding to show the answer?

**Comment by Schlauer-Hax** [comment] 2020-11-03 17:39
I found a workaround: Hold the text next to it to select it and then you can press the boxes and stuff. You maybe have to disable showing the next answer in the settings.

**Comment by zjosua** [comment] 2021-03-15 18:17
Duplicate of #11

**Closed by zjosua** 2021-03-15 18:17 UTC
